import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import bcrypt from 'bcryptjs';
import { createApp } from '../src/app.js';
import { authDatabase } from '../test-support/auth-database.js';

test('Departments API uses the existing schema and ADMIN permission', async t => {
  const db = await authDatabase();
  t.after(() => db.close());
  await db.query(`CREATE TABLE public.departments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE,
    description text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await db.query(`CREATE TRIGGER trg_departments_set_updated_at BEFORE UPDATE ON public.departments
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()`);
  const config = {
    origin: 'http://localhost:5173', jwtSecret: 'departments-test-secret-'.repeat(3),
    initialUserPassword: 'Testpassword123!',
    roles: { admin: 'ADMIN', manager: 'HR_MANAGER', staff: 'HR_STAFF', analyst: 'DATA' },
    auth: { cookieSecure: true, cookieSameSite: 'lax', accessTtlSeconds: 3600, refreshTtlSeconds: 604800 },
  };
  const hash = await bcrypt.hash('InitialPassword123!', 4);
  for (const role of Object.values(config.roles)) await db.query('INSERT INTO public.roles(name) VALUES ($1)', [role]);
  await db.query(`INSERT INTO public.users(email,password_hash,full_name,role_id,status) VALUES
    ('admin@eris.test',$1,'Admin',1,'ACTIVE'),('staff@eris.test',$1,'Staff',3,'ACTIVE')`, [hash]);
  const server = createApp({ db, config, mailer: { configured: true } }).listen(0, '127.0.0.1');
  await once(server, 'listening');
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const request = async (path, { method = 'GET', body, access } = {}) => {
    const response = await fetch(base + path, { method, headers: {
      ...(body ? { 'Content-Type': 'application/json' } : {}),
      ...(access ? { Authorization: `Bearer ${access}` } : {}),
    }, ...(body ? { body: JSON.stringify(body) } : {}) });
    return { status: response.status, body: await response.json() };
  };
  const login = async email => (await request('/api/auth/login', { method: 'POST',
    body: { email, password: 'InitialPassword123!' } })).body.accessToken;
  const admin = await login('admin@eris.test');
  const staff = await login('staff@eris.test');

  assert.equal((await request('/api/departments', { access: staff })).status, 403);
  assert.equal((await request('/api/departments')).status, 401);

  const created = await request('/api/departments', { method: 'POST', access: admin,
    body: { name: 'Engineering', description: 'Product engineering' } });
  assert.equal(created.status, 201);
  assert.equal(created.body.name, 'Engineering');
  assert.equal((await request('/api/departments', { method: 'POST', access: admin,
    body: { name: 'Engineering' } })).status, 409);
  assert.equal((await request('/api/departments', { method: 'POST', access: admin,
    body: { name: '' } })).status, 400);

  const list = await request('/api/departments?q=engine&page=1&limit=10', { access: admin });
  assert.equal(list.status, 200);
  assert.equal(list.body.data.length, 1);

  const updated = await request(`/api/departments/${created.body.id}`, { method: 'PATCH', access: admin,
    body: { name: 'Engineering & Product', description: null } });
  assert.equal(updated.status, 200);
  assert.equal(updated.body.name, 'Engineering & Product');
  assert.equal(updated.body.description, null);
  assert.equal((await request('/api/departments/999999', { method: 'PATCH', access: admin,
    body: { name: 'Missing' } })).status, 404);
  assert.equal((await request(`/api/departments/${created.body.id}`, { method: 'PATCH', access: admin,
    body: { id: 10 } })).status, 400);

  const audits = await db.query(`SELECT action FROM public.audit_logs
    WHERE entity_type='departments' ORDER BY id`);
  assert.deepEqual(audits.rows.map(row => row.action), ['DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED']);
  const columns = await db.query(`SELECT column_name FROM information_schema.columns
    WHERE table_schema='public' AND table_name='departments' ORDER BY ordinal_position`);
  assert.deepEqual(columns.rows.map(row => row.column_name),
    ['id', 'name', 'description', 'created_at', 'updated_at']);
});
