--
-- PostgreSQL database dump
--

\restrict 5tRoYgSPHySr4LklFP4KaY47iPlILrzICYCAtiMAqE4afDqs3mNeHj4IRFohq6F

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.6

-- Started on 2026-09-08 19:34:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 891 (class 1247 OID 16454)
-- Name: employee_outcome_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.employee_outcome_enum AS ENUM (
    'STAYED',
    'RESIGNED',
    'TERMINATED'
);


ALTER TYPE public.employee_outcome_enum OWNER TO talentguard;

--
-- TOC entry 876 (class 1247 OID 16404)
-- Name: employment_status_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.employment_status_enum AS ENUM (
    'ACTIVE',
    'RESIGNED',
    'TERMINATED'
);


ALTER TYPE public.employment_status_enum OWNER TO talentguard;

--
-- TOC entry 873 (class 1247 OID 16396)
-- Name: gender_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.gender_enum AS ENUM (
    'MALE',
    'FEMALE',
    'OTHER'
);


ALTER TYPE public.gender_enum OWNER TO talentguard;

--
-- TOC entry 882 (class 1247 OID 16420)
-- Name: impact_direction_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.impact_direction_enum AS ENUM (
    'POSITIVE',
    'NEGATIVE',
    'NEUTRAL'
);


ALTER TYPE public.impact_direction_enum OWNER TO talentguard;

--
-- TOC entry 888 (class 1247 OID 16444)
-- Name: retention_action_status_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.retention_action_status_enum AS ENUM (
    'PLANNED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);


ALTER TYPE public.retention_action_status_enum OWNER TO talentguard;

--
-- TOC entry 885 (class 1247 OID 16428)
-- Name: retention_action_type_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.retention_action_type_enum AS ENUM (
    'MEETING',
    'SALARY_REVIEW',
    'PROMOTION_REVIEW',
    'TRAINING',
    'WORKLOAD_ADJUSTMENT',
    'CAREER_DISCUSSION',
    'OTHER'
);


ALTER TYPE public.retention_action_type_enum OWNER TO talentguard;

--
-- TOC entry 879 (class 1247 OID 16412)
-- Name: risk_level_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.risk_level_enum AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH'
);


ALTER TYPE public.risk_level_enum OWNER TO talentguard;

--
-- TOC entry 870 (class 1247 OID 16391)
-- Name: user_status_enum; Type: TYPE; Schema: public; Owner: talentguard
--

CREATE TYPE public.user_status_enum AS ENUM (
    'ACTIVE',
    'INACTIVE'
);


ALTER TYPE public.user_status_enum OWNER TO talentguard;

--
-- TOC entry 241 (class 1255 OID 16461)
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: talentguard
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO talentguard;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 240 (class 1259 OID 16658)
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.audit_logs (
    id integer NOT NULL,
    user_id integer,
    action character varying(100) NOT NULL,
    entity_type character varying(100),
    entity_id integer,
    details jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.audit_logs OWNER TO talentguard;

--
-- TOC entry 239 (class 1259 OID 16657)
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16490)
-- Name: departments; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.departments (
    id integer NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.departments OWNER TO talentguard;

--
-- TOC entry 221 (class 1259 OID 16489)
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16639)
-- Name: employee_outcomes; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.employee_outcomes (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    outcome public.employee_outcome_enum NOT NULL,
    outcome_date date NOT NULL,
    reason text,
    recorded_by integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.employee_outcomes OWNER TO talentguard;

--
-- TOC entry 237 (class 1259 OID 16638)
-- Name: employee_outcomes_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.employee_outcomes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_outcomes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16543)
-- Name: employee_snapshots; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.employee_snapshots (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    snapshot_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    monthly_income numeric(15,2),
    years_at_company numeric(5,2),
    years_in_current_role numeric(5,2),
    job_satisfaction smallint,
    environment_satisfaction smallint,
    work_life_balance smallint,
    job_involvement smallint,
    performance_rating smallint,
    overtime boolean,
    distance_from_home numeric(10,2),
    training_times_last_year integer,
    years_since_last_promotion numeric(5,2),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_environment_satisfaction CHECK (((environment_satisfaction IS NULL) OR ((environment_satisfaction >= 1) AND (environment_satisfaction <= 5)))),
    CONSTRAINT chk_job_involvement CHECK (((job_involvement IS NULL) OR ((job_involvement >= 1) AND (job_involvement <= 5)))),
    CONSTRAINT chk_job_satisfaction CHECK (((job_satisfaction IS NULL) OR ((job_satisfaction >= 1) AND (job_satisfaction <= 5)))),
    CONSTRAINT chk_monthly_income CHECK (((monthly_income IS NULL) OR (monthly_income >= (0)::numeric))),
    CONSTRAINT chk_performance_rating CHECK (((performance_rating IS NULL) OR ((performance_rating >= 1) AND (performance_rating <= 5)))),
    CONSTRAINT chk_work_life_balance CHECK (((work_life_balance IS NULL) OR ((work_life_balance >= 1) AND (work_life_balance <= 5)))),
    CONSTRAINT chk_years_at_company CHECK (((years_at_company IS NULL) OR (years_at_company >= (0)::numeric))),
    CONSTRAINT chk_years_current_role CHECK (((years_in_current_role IS NULL) OR (years_in_current_role >= (0)::numeric)))
);


ALTER TABLE public.employee_snapshots OWNER TO talentguard;

--
-- TOC entry 227 (class 1259 OID 16542)
-- Name: employee_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.employee_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16514)
-- Name: employees; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.employees (
    id integer NOT NULL,
    employee_code character varying(50) NOT NULL,
    full_name character varying(150) NOT NULL,
    email character varying(255),
    gender public.gender_enum,
    date_of_birth date,
    hire_date date NOT NULL,
    department_id integer,
    position_id integer,
    manager_id integer,
    employment_status public.employment_status_enum DEFAULT 'ACTIVE'::public.employment_status_enum NOT NULL,
    salary numeric(15,2),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_employee_salary CHECK (((salary IS NULL) OR (salary >= (0)::numeric)))
);


ALTER TABLE public.employees OWNER TO talentguard;

--
-- TOC entry 225 (class 1259 OID 16513)
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16564)
-- Name: model_versions; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.model_versions (
    id integer NOT NULL,
    version character varying(50) NOT NULL,
    model_name character varying(100) NOT NULL,
    accuracy numeric(6,5),
    precision_score numeric(6,5),
    recall_score numeric(6,5),
    f1_score numeric(6,5),
    is_active boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_accuracy CHECK (((accuracy IS NULL) OR ((accuracy >= (0)::numeric) AND (accuracy <= (1)::numeric)))),
    CONSTRAINT chk_f1 CHECK (((f1_score IS NULL) OR ((f1_score >= (0)::numeric) AND (f1_score <= (1)::numeric)))),
    CONSTRAINT chk_precision CHECK (((precision_score IS NULL) OR ((precision_score >= (0)::numeric) AND (precision_score <= (1)::numeric)))),
    CONSTRAINT chk_recall CHECK (((recall_score IS NULL) OR ((recall_score >= (0)::numeric) AND (recall_score <= (1)::numeric))))
);


ALTER TABLE public.model_versions OWNER TO talentguard;

--
-- TOC entry 229 (class 1259 OID 16563)
-- Name: model_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.model_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16502)
-- Name: positions; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.positions (
    id integer NOT NULL,
    title character varying(150) NOT NULL,
    level character varying(50),
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.positions OWNER TO talentguard;

--
-- TOC entry 223 (class 1259 OID 16501)
-- Name: positions_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16601)
-- Name: prediction_factors; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.prediction_factors (
    id integer NOT NULL,
    prediction_id integer NOT NULL,
    factor_name character varying(150) NOT NULL,
    factor_value character varying(255),
    importance_score numeric(10,6),
    impact_direction public.impact_direction_enum,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.prediction_factors OWNER TO talentguard;

--
-- TOC entry 233 (class 1259 OID 16600)
-- Name: prediction_factors_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.prediction_factors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prediction_factors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16578)
-- Name: predictions; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.predictions (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    snapshot_id integer NOT NULL,
    model_version_id integer NOT NULL,
    risk_score numeric(6,5) NOT NULL,
    risk_level public.risk_level_enum NOT NULL,
    predicted_attrition boolean NOT NULL,
    predicted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_risk_score CHECK (((risk_score >= (0)::numeric) AND (risk_score <= (1)::numeric)))
);


ALTER TABLE public.predictions OWNER TO talentguard;

--
-- TOC entry 231 (class 1259 OID 16577)
-- Name: predictions_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.predictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.predictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16613)
-- Name: retention_actions; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.retention_actions (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    prediction_id integer,
    created_by integer NOT NULL,
    action_type public.retention_action_type_enum NOT NULL,
    description text,
    status public.retention_action_status_enum DEFAULT 'PLANNED'::public.retention_action_status_enum NOT NULL,
    scheduled_date timestamp without time zone,
    completed_at timestamp without time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.retention_actions OWNER TO talentguard;

--
-- TOC entry 235 (class 1259 OID 16612)
-- Name: retention_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.retention_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retention_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16463)
-- Name: roles; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.roles OWNER TO talentguard;

--
-- TOC entry 217 (class 1259 OID 16462)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16472)
-- Name: users; Type: TABLE; Schema: public; Owner: talentguard
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    full_name character varying(150) NOT NULL,
    role_id integer NOT NULL,
    status public.user_status_enum DEFAULT 'ACTIVE'::public.user_status_enum NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.users OWNER TO talentguard;

--
-- TOC entry 219 (class 1259 OID 16471)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: talentguard
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3445 (class 2606 OID 16665)
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 3400 (class 2606 OID 16500)
-- Name: departments departments_name_key; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_name_key UNIQUE (name);


--
-- TOC entry 3402 (class 2606 OID 16498)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- TOC entry 3442 (class 2606 OID 16646)
-- Name: employee_outcomes employee_outcomes_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employee_outcomes
    ADD CONSTRAINT employee_outcomes_pkey PRIMARY KEY (id);


--
-- TOC entry 3418 (class 2606 OID 16557)
-- Name: employee_snapshots employee_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employee_snapshots
    ADD CONSTRAINT employee_snapshots_pkey PRIMARY KEY (id);


--
-- TOC entry 3408 (class 2606 OID 16526)
-- Name: employees employees_email_key; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_email_key UNIQUE (email);


--
-- TOC entry 3410 (class 2606 OID 16524)
-- Name: employees employees_employee_code_key; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_employee_code_key UNIQUE (employee_code);


--
-- TOC entry 3412 (class 2606 OID 16522)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- TOC entry 3422 (class 2606 OID 16574)
-- Name: model_versions model_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.model_versions
    ADD CONSTRAINT model_versions_pkey PRIMARY KEY (id);


--
-- TOC entry 3424 (class 2606 OID 16576)
-- Name: model_versions model_versions_version_key; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.model_versions
    ADD CONSTRAINT model_versions_version_key UNIQUE (version);


--
-- TOC entry 3404 (class 2606 OID 16510)
-- Name: positions positions_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT positions_pkey PRIMARY KEY (id);


--
-- TOC entry 3434 (class 2606 OID 16606)
-- Name: prediction_factors prediction_factors_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.prediction_factors
    ADD CONSTRAINT prediction_factors_pkey PRIMARY KEY (id);


--
-- TOC entry 3431 (class 2606 OID 16584)
-- Name: predictions predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_pkey PRIMARY KEY (id);


--
-- TOC entry 3440 (class 2606 OID 16622)
-- Name: retention_actions retention_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.retention_actions
    ADD CONSTRAINT retention_actions_pkey PRIMARY KEY (id);


--
-- TOC entry 3391 (class 2606 OID 16470)
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- TOC entry 3393 (class 2606 OID 16468)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3406 (class 2606 OID 16512)
-- Name: positions uq_position_title_level; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT uq_position_title_level UNIQUE (title, level);


--
-- TOC entry 3396 (class 2606 OID 16483)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3398 (class 2606 OID 16481)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3446 (class 1259 OID 16696)
-- Name: idx_audit_details_gin; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_audit_details_gin ON public.audit_logs USING gin (details);


--
-- TOC entry 3447 (class 1259 OID 16695)
-- Name: idx_audit_entity; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_audit_entity ON public.audit_logs USING btree (entity_type, entity_id);


--
-- TOC entry 3448 (class 1259 OID 16694)
-- Name: idx_audit_user; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_audit_user ON public.audit_logs USING btree (user_id);


--
-- TOC entry 3413 (class 1259 OID 16677)
-- Name: idx_employees_department; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_employees_department ON public.employees USING btree (department_id);


--
-- TOC entry 3414 (class 1259 OID 16679)
-- Name: idx_employees_manager; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_employees_manager ON public.employees USING btree (manager_id);


--
-- TOC entry 3415 (class 1259 OID 16678)
-- Name: idx_employees_position; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_employees_position ON public.employees USING btree (position_id);


--
-- TOC entry 3416 (class 1259 OID 16680)
-- Name: idx_employees_status; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_employees_status ON public.employees USING btree (employment_status);


--
-- TOC entry 3443 (class 1259 OID 16693)
-- Name: idx_outcomes_employee; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_outcomes_employee ON public.employee_outcomes USING btree (employee_id);


--
-- TOC entry 3432 (class 1259 OID 16688)
-- Name: idx_prediction_factors_prediction; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_prediction_factors_prediction ON public.prediction_factors USING btree (prediction_id);


--
-- TOC entry 3425 (class 1259 OID 16683)
-- Name: idx_predictions_employee; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_predictions_employee ON public.predictions USING btree (employee_id);


--
-- TOC entry 3426 (class 1259 OID 16686)
-- Name: idx_predictions_employee_date; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_predictions_employee_date ON public.predictions USING btree (employee_id, predicted_at);


--
-- TOC entry 3427 (class 1259 OID 16685)
-- Name: idx_predictions_model; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_predictions_model ON public.predictions USING btree (model_version_id);


--
-- TOC entry 3428 (class 1259 OID 16687)
-- Name: idx_predictions_risk_level; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_predictions_risk_level ON public.predictions USING btree (risk_level);


--
-- TOC entry 3429 (class 1259 OID 16684)
-- Name: idx_predictions_snapshot; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_predictions_snapshot ON public.predictions USING btree (snapshot_id);


--
-- TOC entry 3435 (class 1259 OID 16691)
-- Name: idx_retention_created_by; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_retention_created_by ON public.retention_actions USING btree (created_by);


--
-- TOC entry 3436 (class 1259 OID 16689)
-- Name: idx_retention_employee; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_retention_employee ON public.retention_actions USING btree (employee_id);


--
-- TOC entry 3437 (class 1259 OID 16690)
-- Name: idx_retention_prediction; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_retention_prediction ON public.retention_actions USING btree (prediction_id);


--
-- TOC entry 3438 (class 1259 OID 16692)
-- Name: idx_retention_status; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_retention_status ON public.retention_actions USING btree (status);


--
-- TOC entry 3419 (class 1259 OID 16681)
-- Name: idx_snapshots_employee; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_snapshots_employee ON public.employee_snapshots USING btree (employee_id);


--
-- TOC entry 3420 (class 1259 OID 16682)
-- Name: idx_snapshots_employee_date; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_snapshots_employee_date ON public.employee_snapshots USING btree (employee_id, snapshot_date);


--
-- TOC entry 3394 (class 1259 OID 16676)
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: talentguard
--

CREATE INDEX idx_users_role ON public.users USING btree (role_id);


--
-- TOC entry 3465 (class 2620 OID 16672)
-- Name: departments trg_departments_set_updated_at; Type: TRIGGER; Schema: public; Owner: talentguard
--

CREATE TRIGGER trg_departments_set_updated_at BEFORE UPDATE ON public.departments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 3467 (class 2620 OID 16674)
-- Name: employees trg_employees_set_updated_at; Type: TRIGGER; Schema: public; Owner: talentguard
--

CREATE TRIGGER trg_employees_set_updated_at BEFORE UPDATE ON public.employees FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 3466 (class 2620 OID 16673)
-- Name: positions trg_positions_set_updated_at; Type: TRIGGER; Schema: public; Owner: talentguard
--

CREATE TRIGGER trg_positions_set_updated_at BEFORE UPDATE ON public.positions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 3468 (class 2620 OID 16675)
-- Name: retention_actions trg_retention_actions_set_updated_at; Type: TRIGGER; Schema: public; Owner: talentguard
--

CREATE TRIGGER trg_retention_actions_set_updated_at BEFORE UPDATE ON public.retention_actions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 3464 (class 2620 OID 16671)
-- Name: users trg_users_set_updated_at; Type: TRIGGER; Schema: public; Owner: talentguard
--

CREATE TRIGGER trg_users_set_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 3463 (class 2606 OID 16666)
-- Name: audit_logs fk_audit_user; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 3450 (class 2606 OID 16527)
-- Name: employees fk_employee_department; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- TOC entry 3451 (class 2606 OID 16537)
-- Name: employees fk_employee_manager; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- TOC entry 3452 (class 2606 OID 16532)
-- Name: employees fk_employee_position; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employee_position FOREIGN KEY (position_id) REFERENCES public.positions(id) ON DELETE SET NULL;


--
-- TOC entry 3457 (class 2606 OID 16607)
-- Name: prediction_factors fk_factor_prediction; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.prediction_factors
    ADD CONSTRAINT fk_factor_prediction FOREIGN KEY (prediction_id) REFERENCES public.predictions(id) ON DELETE CASCADE;


--
-- TOC entry 3461 (class 2606 OID 16647)
-- Name: employee_outcomes fk_outcome_employee; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employee_outcomes
    ADD CONSTRAINT fk_outcome_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- TOC entry 3462 (class 2606 OID 16652)
-- Name: employee_outcomes fk_outcome_recorded_by; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employee_outcomes
    ADD CONSTRAINT fk_outcome_recorded_by FOREIGN KEY (recorded_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 3454 (class 2606 OID 16585)
-- Name: predictions fk_prediction_employee; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT fk_prediction_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- TOC entry 3455 (class 2606 OID 16595)
-- Name: predictions fk_prediction_model; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT fk_prediction_model FOREIGN KEY (model_version_id) REFERENCES public.model_versions(id) ON DELETE RESTRICT;


--
-- TOC entry 3456 (class 2606 OID 16590)
-- Name: predictions fk_prediction_snapshot; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT fk_prediction_snapshot FOREIGN KEY (snapshot_id) REFERENCES public.employee_snapshots(id) ON DELETE RESTRICT;


--
-- TOC entry 3458 (class 2606 OID 16633)
-- Name: retention_actions fk_retention_created_by; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.retention_actions
    ADD CONSTRAINT fk_retention_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- TOC entry 3459 (class 2606 OID 16623)
-- Name: retention_actions fk_retention_employee; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.retention_actions
    ADD CONSTRAINT fk_retention_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- TOC entry 3460 (class 2606 OID 16628)
-- Name: retention_actions fk_retention_prediction; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.retention_actions
    ADD CONSTRAINT fk_retention_prediction FOREIGN KEY (prediction_id) REFERENCES public.predictions(id) ON DELETE SET NULL;


--
-- TOC entry 3453 (class 2606 OID 16558)
-- Name: employee_snapshots fk_snapshot_employee; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.employee_snapshots
    ADD CONSTRAINT fk_snapshot_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- TOC entry 3449 (class 2606 OID 16484)
-- Name: users fk_users_role; Type: FK CONSTRAINT; Schema: public; Owner: talentguard
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE RESTRICT;


-- Completed on 2026-09-08 19:34:35

--
-- PostgreSQL database dump complete
--

\unrestrict 5tRoYgSPHySr4LklFP4KaY47iPlILrzICYCAtiMAqE4afDqs3mNeHj4IRFohq6F

